wiki/encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "encyclopedia"

urlpatterns = [
    path("", views.index, name="index"),
    path("search", views.search, name="search"),
    path("newpage", views.newpage, name="newpage"),
    path("random", views.random_page, name="random"),
    path("<str:title>/edit", views.edit, name="edit"),
    path("<str:title>", views.entry, name="entry"),
]

wiki/wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

wiki/encyclopedia/models.py
from django.db import models

# Create your models here.

wiki/encyclopedia/views.py
import markdown2
from django import forms
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
import random
from . import util

class NewPageForm(forms.Form):
    title = forms.CharField(widget=forms.TextInput(attrs={"name":"title"}), label="Title")
    content = forms.CharField(widget=forms.Textarea(attrs={"name":"content", "rows":"5"}), label="Markdown")

class EditEntryForm(forms.Form):
    content = forms.CharField(widget=forms.Textarea())


def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })


def entry(request, title):
    # If entry not found, show error
    if not (entry := util.get_entry(title)):
        title = "Error"
        entry = "Error: Page not found."
    # Otherwise show entry's markdown contents
    return render(request, "encyclopedia/entry.html", {
        "title": title,
        "content": markdown2.markdown(entry),
    })


def search(request):
    query = request.GET.get("q")
    # If there is an entry that matches that title
    if query in util.list_entries():
        entry = util.get_entry(query)
        return render(request, "encyclopedia/entry.html", {
            "title": query,
            "content": markdown2.markdown(entry)
        })
    else:
        # List for pages with matching substring
        matches = []
        # Check each entry for presence of substring
        for title in util.list_entries():
            if query in markdown2.markdown(util.get_entry(title)):
                matches.append(title)
        return render(request, "encyclopedia/search.html", {
            "matches": matches
        })


def newpage(request):
    # Submit new page form
    if request.method == "POST":
        form = NewPageForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data["title"]
            content = form.cleaned_data["content"]
            if util.get_entry(title):
                return render(request, "encyclopedia/newpage.html", {
                    "form": form,
                    "error": "An entry with this title already exists."
                })
            else:
                # Save new page entry
                util.save_entry(title, content)
                # Redirect to the new page
                return redirect("encyclopedia:entry", title=title)
        else:
            return render(request, "encyclopedia/newpage.html", {
                "form": form,
            })
    # Show new page form
    return render(request, "encyclopedia/newpage.html", {
        "form": NewPageForm(),
    })


def edit(request, title):
    content = util.get_entry(title)

    if content is None:
        return render(request, "encyclopedia.error.html", {
            "message": "This entry does not exist."
        })
    
    if request.method == "POST":
        form = EditEntryForm(request.POST)
        if form.is_valid():
            # Save edited page content
            util.save_entry(title, form.cleaned_data["content"])
            # Redirect to the new page
            return redirect("encyclopedia:entry", title=title)
    else:
        form = EditEntryForm(initial={"title": title, "content": content})

    return render(request, "encyclopedia/edit.html", {
        "form": form,
        "title": title,
    })


def random_page(request):
    entries = util.list_entries()
    if entries:
        random_entry = random.choice(entries)
        return redirect("encyclopedia:entry", title=random_entry)
    else:
        return render(request, "encyclopedia/error.html", {
            "message": "No entries available",
        })

wiki/encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ title }}
{% endblock %}

{% block body %}

    <h1>Edit: {{ title }}</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Save">
    </form>
    
    {{ content|safe }}

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ title }}
{% endblock %}

{% block body %}

    <a href="{% url 'encyclopedia:edit' title=title %}" class="btn btn-primary">Edit Page</a>
    
    {{ content|safe }}

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/error.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Error
{% endblock %}

{% block body %}
    
    <h1 text-align="center">Error: Not found</h1>

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li><a href="{% url 'encyclopedia:entry' entry %}">{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'encyclopedia:search' %}" method="get">
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:newpage' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:random' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

wiki/encyclopedia/templates/encyclopedia/newpage.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    New Page
{% endblock %}

{% block body %}
    
    <h1>New Page</h1>

    {% if error %}
        <p style="color: red;">{{ error }}</p>
    {% endif %}

    <a href="https://guides.github.com/features/mastering-markdown/">Markdown guides</a>

    <form action="{% url 'encyclopedia:newpage' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <div class="form-group">
            <input type="submit" value="Create Page">
        </div>
    </form>

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/search.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Results
{% endblock %}

{% block body %}

    <h1>Results</h1>
    <ul>
        {% for match in matches %}
            <li><a href="{% url 'encyclopedia:entry' match %}">{{ match }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}